version: 0.2

phases:
  install:
    commands:
      - echo "Build phase not deploying. Only preparing artifacts."

phases:
  build:
    commands:
      - echo "Preparing Kubernetes manifests for Lambda deployment"

artifacts:
  files:
    - deployment.yaml
    - service.yaml
  discard-paths: yes
